[phases.setup]
aptPkgs = ["python3", "gcc", "g++", "make", "libvips-dev", "pkg-config"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
